// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS9zbPq-yy1w5byAAqUHQN2EOr4s4lfeE',
    appId: '1:890020745806:web:0a733ab597d03aaedc691f',
    messagingSenderId: '890020745806',
    projectId: 'qur-an-rag',
    authDomain: 'qur-an-rag.firebaseapp.com',
    storageBucket: 'qur-an-rag.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfy91pSOc-dIxZY3AMBQoU7BdnZ-6DV2M',
    appId: '1:890020745806:android:0de00f76b2ce33addc691f',
    messagingSenderId: '890020745806',
    projectId: 'qur-an-rag',
    storageBucket: 'qur-an-rag.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH1ONZjH8MCf7qoMfZ7XV7SReyPITrTAc',
    appId: '1:890020745806:ios:3ecf8d4f4328503ddc691f',
    messagingSenderId: '890020745806',
    projectId: 'qur-an-rag',
    storageBucket: 'qur-an-rag.firebasestorage.app',
    androidClientId: '890020745806-q9d9ei0fmp8en0apan9jm13uo158oe3r.apps.googleusercontent.com',
    iosClientId: '890020745806-v0ls9fck06fi66gunl89rv60d6bia131.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH1ONZjH8MCf7qoMfZ7XV7SReyPITrTAc',
    appId: '1:890020745806:ios:3ecf8d4f4328503ddc691f',
    messagingSenderId: '890020745806',
    projectId: 'qur-an-rag',
    storageBucket: 'qur-an-rag.firebasestorage.app',
    androidClientId: '890020745806-q9d9ei0fmp8en0apan9jm13uo158oe3r.apps.googleusercontent.com',
    iosClientId: '890020745806-v0ls9fck06fi66gunl89rv60d6bia131.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS9zbPq-yy1w5byAAqUHQN2EOr4s4lfeE',
    appId: '1:890020745806:web:c2df8ed9d63197d3dc691f',
    messagingSenderId: '890020745806',
    projectId: 'qur-an-rag',
    authDomain: 'qur-an-rag.firebaseapp.com',
    storageBucket: 'qur-an-rag.firebasestorage.app',
  );

}